### ISSUE TITLE
broken link in situation report April 3

### ISSUE THREAD

**Issue by JiscaH** [nextstrain/narratives#4]
On slide 10 (Iceland) of the latest situation report, there are double brackets around the link to the WHO report, causing an error when one clicks on it:

# [Extensive sequencing by Iceland highlights extent of travel-associated spread](https://nextstrain.org/ncov/2020-04-03?c=country_exposure&f_country=Iceland&p=grid&d=tree,map&legend=open)
We recently received 301 sequences -- from 25\% of [confirmed cases]((https://www.who.int/docs/default-source/coronaviruse/situation-reports/20200402-sitrep-73-covid-19.pdf)) -- from Iceland.
<br><br>

**Comment by emmahodcroft** [comment]
Thank you for spotting this @JiscaH ! Good eye!!  I've fixed this in the English language live version right now - and I'll tag @cassiawag so she can alert other translators to this error! (Cassia, I don't want to mess things up by wading in to try and fix this when I know you've got good teams working & I don't want to unexpectedly change their flow- so I'm going to let you handle this - hope that's ok!)

Thanks again @JiscaH !  👏

**Comment by cassiawag** [comment]
Thanks so much@JiscaH! I'll make sure this is fixed in all translations :)
